"""Simulate a full review-bot run against a real PR with a mocked LLM response.

Usage:
    GITHUB_TOKEN=$(gh auth token) uv run python scripts/simulate_review.py

Posts real comments to PR #1 on dawidbudaszewski/fastify.
"""

import json
import logging
from unittest.mock import MagicMock, patch

from src.approval_agent import agent as approval_agent
from src.github.client import GitHubClient
from src.review_agent import agent as review_agent

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")

MOCK_LLM_RESPONSE = json.dumps({
    "summary": (
        "This PR adds a new example endpoint for user management with login and user lookup. "
        "The implementation introduces several critical security vulnerabilities:\n\n"
        "**Architecture Changes:**\n"
        "- Adds a `/users` GET endpoint that queries a database for user records\n"
        "- Adds a `/login` POST endpoint with password-based authentication\n"
        "- Starts the server on port 3000\n\n"
        "**Security Concerns:**\n"
        "- SQL query is constructed via string interpolation, enabling injection attacks\n"
        "- Authentication credentials are hardcoded in the source file\n"
        "- Token generation uses a predictable concatenation of username and timestamp\n"
        "- Password comparison uses loose equality, potentially allowing type coercion bypasses"
    ),
    "confidence_score": 1,
    "findings": [
        {
            "file": "examples/insecure-endpoint.js",
            "line": 6,
            "severity": "P0",
            "category": "security",
            "description": "Hardcoded password in source code exposes credentials to anyone with repository access.",
            "suggested_fix": "const PASSWORD = process.env.LOGIN_PASSWORD",
        },
        {
            "file": "examples/insecure-endpoint.js",
            "line": 9,
            "severity": "P0",
            "category": "security",
            "description": "SQL injection vulnerability: user input is interpolated directly into a SQL query string.",
            "suggested_fix": "const query = 'SELECT * FROM users WHERE id = $1';\nconst result = await fastify.db.query(query, [userId]);",
        },
        {
            "file": "examples/insecure-endpoint.js",
            "line": 16,
            "severity": "P1",
            "category": "logic",
            "description": "Loose equality (==) used for password comparison; use strict equality (===) to avoid type coercion bypasses.",
            "suggested_fix": "if (password === PASSWORD) {",
        },
        {
            "file": "examples/insecure-endpoint.js",
            "line": 17,
            "severity": "P1",
            "category": "security",
            "description": "Token is generated by concatenating username with timestamp, which is predictable and insecure.",
            "suggested_fix": None,
        },
        {
            "file": "examples/insecure-endpoint.js",
            "line": 11,
            "severity": "P2",
            "category": "logic",
            "description": "No input validation on request.query.id; should validate it is a numeric value before use.",
            "suggested_fix": None,
        },
    ],
})


def main() -> None:
    import os

    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("ERROR: Set GITHUB_TOKEN. Run: export GITHUB_TOKEN=$(gh auth token)")
        return

    repo = "dawidbudaszewski/fastify"
    pr_number = 1

    github = GitHubClient(token=token, repo=repo, pr_number=pr_number)

    with patch("src.review_agent.agent.completion") as mock_completion:
        mock_completion.return_value = MagicMock(
            choices=[MagicMock(message=MagicMock(content=MOCK_LLM_RESPONSE))]
        )

        print("\n=== Phase 1: Review Agent ===")
        result = review_agent.run(github=github, litellm_api_key="mocked")

        print(f"\nReview Result: {result.confidence_score}/5, {len(result.findings)} findings")
        for f in result.findings:
            print(f"  [{f.severity.value}] {f.file}:{f.line} - {f.description}")

    print("\n=== Phase 2: Approval Agent (reads from PR independently) ===")
    approval_agent.run(github=github)

    print(f"\nDone! Check the PR: https://github.com/{repo}/pull/{pr_number}")


if __name__ == "__main__":
    main()
