import Link from "next/link";
import { notFound } from "next/navigation";
import { getPRDetail } from "@/lib/github";
import { ReviewSummaryCard } from "@/components/review-summary";
import { FindingsTable } from "@/components/finding-card";
import { Timeline } from "@/components/timeline";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

export const dynamic = "force-dynamic";

function StateBadge({ state }: { state: string }) {
  switch (state) {
    case "merged":
      return (
        <Badge className="bg-purple-100 text-purple-700 hover:bg-purple-100 border-0">
          Merged
        </Badge>
      );
    case "closed":
      return (
        <Badge className="bg-red-50 text-red-600 hover:bg-red-50 border-0">
          Closed
        </Badge>
      );
    default:
      return (
        <Badge className="bg-emerald-50 text-emerald-700 hover:bg-emerald-50 border-0">
          Open
        </Badge>
      );
  }
}

export default async function PRDetailPage({
  params,
}: {
  params: Promise<{ number: string }>;
}) {
  const { number } = await params;
  const prNumber = parseInt(number, 10);
  if (isNaN(prNumber)) notFound();

  let pr;
  try {
    pr = await getPRDetail(prNumber);
  } catch {
    notFound();
  }

  return (
    <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
      <div className="mb-6">
        <Link
          href="/"
          className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          ← Back to dashboard
        </Link>
      </div>

      <div className="mb-8">
        <div className="flex items-start gap-3">
          <h1 className="text-2xl font-semibold tracking-tight">
            <span className="text-muted-foreground font-normal">#{pr.number}</span>{" "}
            {pr.title}
          </h1>
          <StateBadge state={pr.state} />
        </div>
        <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground">
          <span>
            by <span className="text-foreground font-medium">{pr.author}</span>
          </span>
          <span className="font-mono text-xs">
            {pr.headBranch} → {pr.baseBranch}
          </span>
          <span>Opened {new Date(pr.createdAt).toLocaleDateString()}</span>
          <a
            href={pr.htmlUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline underline-offset-4"
          >
            View on GitHub ↗
          </a>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-8">
          <section>
            <h2 className="text-base font-medium mb-4">Review Overview</h2>
            <ReviewSummaryCard review={pr.review} />
          </section>

          {pr.review.summary && (
            <section>
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Review Summary</CardTitle>
                  <CardDescription>Generated by review-bot</CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">
                    {pr.review.summary}
                  </p>
                </CardContent>
              </Card>
            </section>
          )}

          {pr.review.findings.length > 0 && (
            <section>
              <h2 className="text-base font-medium mb-4">
                Findings ({pr.review.findings.length})
              </h2>
              <FindingsTable findings={pr.review.findings} />
            </section>
          )}
        </div>

        <div className="lg:col-span-1">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Activity</CardTitle>
              <CardDescription>PR lifecycle events</CardDescription>
            </CardHeader>
            <CardContent>
              <Timeline events={pr.timeline} />
            </CardContent>
          </Card>
        </div>
      </div>
    </main>
  );
}
