import Link from "next/link";
import { notFound } from "next/navigation";
import { getPRDetail } from "@/lib/github";
import { ReviewSummaryCard } from "@/components/review-summary";
import { FindingsTable } from "@/components/finding-card";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

export const dynamic = "force-dynamic";

export default async function PRDetailPage({
  params,
}: {
  params: Promise<{ number: string }>;
}) {
  const { number } = await params;
  const prNumber = parseInt(number, 10);
  if (isNaN(prNumber)) notFound();

  let pr;
  try {
    pr = await getPRDetail(prNumber);
  } catch {
    notFound();
  }

  return (
    <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-10">
      <div className="mb-2">
        <Link
          href="/"
          className="text-sm text-muted-foreground hover:text-foreground"
        >
          ← Back to all PRs
        </Link>
      </div>

      <div className="mb-8">
        <div className="flex items-start gap-3">
          <h1 className="text-2xl font-bold tracking-tight">
            #{pr.number} {pr.title}
          </h1>
          <Badge variant="outline" className="capitalize mt-1">
            {pr.state}
          </Badge>
        </div>
        <div className="mt-1.5 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground">
          <span>
            by <strong className="text-foreground">{pr.author}</strong>
          </span>
          <span>
            {pr.headBranch} → {pr.baseBranch}
          </span>
          <span>Opened {new Date(pr.createdAt).toLocaleDateString()}</span>
          <a
            href={pr.htmlUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline"
          >
            View on GitHub ↗
          </a>
        </div>
      </div>

      <section className="mb-8">
        <h2 className="text-lg font-semibold mb-4">Review Overview</h2>
        <ReviewSummaryCard review={pr.review} />
      </section>

      {pr.review.summary && (
        <section className="mb-8">
          <Card>
            <CardHeader>
              <CardTitle>Review Summary</CardTitle>
              <CardDescription>Generated by review-bot</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-relaxed whitespace-pre-wrap">
                {pr.review.summary}
              </p>
            </CardContent>
          </Card>
        </section>
      )}

      <section className="mb-8">
        <h2 className="text-lg font-semibold mb-4">
          Findings ({pr.review.findings.length})
        </h2>
        <FindingsTable findings={pr.review.findings} />
      </section>

      {pr.review.approvalComment && (
        <section className="mb-8">
          <Card>
            <CardHeader>
              <CardTitle>Approval Agent Decision</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-sm leading-relaxed whitespace-pre-wrap font-mono bg-muted rounded-lg p-4">
                {pr.review.approvalComment}
              </div>
            </CardContent>
          </Card>
        </section>
      )}
    </main>
  );
}
